# Generated by Django 5.1 on 2024-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_quizdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdata',
            name='correct',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='word',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
