# Generated by Django 5.1 on 2024-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_modedata_name_alter_userdata_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworddata',
            name='period',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userworddata',
            name='probability',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userworddata',
            name='correct',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userworddata',
            name='quiz',
            field=models.IntegerField(default=1),
        ),
    ]
