# Generated by Django 5.1 on 2024-08-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userworddata_period_userworddata_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworddata',
            name='probability',
            field=models.FloatField(default=1),
        ),
    ]
