# Generated by Django 5.1 on 2024-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_quizdata_correct_alter_quizdata_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdata',
            name='user',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
