# Generated by Django 5.1 on 2024-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_quizdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworddata',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userworddata',
            name='probability',
            field=models.FloatField(default=5),
        ),
    ]
