# Generated by Django 5.1 on 2024-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_chatdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='answer_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
