# Generated by Django 5.1 on 2024-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_chatdata_answer_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='answer_list',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='chat_list',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
