# Generated by Django 5.1 on 2024-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_chatdata_chat_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdata',
            name='answer_list',
        ),
        migrations.RemoveField(
            model_name='chatdata',
            name='chat_list',
        ),
        migrations.AddField(
            model_name='chatdata',
            name='llm',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatdata',
            name='message',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatdata',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatdata',
            name='user',
            field=models.IntegerField(),
        ),
    ]
